In [1]:
import numpy as np

In [2]:
#message passing in simple graph convolution
adjacency_matrix = np.array([
    [0, 1, 0, 0, 1],
    [1, 0, 0, 1, 1],
    [0, 0, 0, 0, 1],
    [0, 1, 0, 0, 0],
    [1, 1, 1, 0, 0]
])

node_feature = np.array([
    [2, 1, 1, 2],
    [1, 2, 2, 1],
    [3, 1, 1, 3],
    [1, 3, 3, 1],
    [1, 1, 3, 2]
])
adjacency_matrix.shape, node_feature.shape

((5, 5), (5, 4))

In [3]:
I = np.identity(5)

node_degree = np.array([2,3,1,1,3])
D = np.diag(node_degree)
D_tilda = np.diag(node_degree+1)
I,D,D_tilda

(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 array([[2, 0, 0, 0, 0],
        [0, 3, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 3]]),
 array([[3, 0, 0, 0, 0],
        [0, 4, 0, 0, 0],
        [0, 0, 2, 0, 0],
        [0, 0, 0, 2, 0],
        [0, 0, 0, 0, 4]]))

In [4]:
adjacency_matrix_tilda = adjacency_matrix + I
adjacency_matrix_tilda,D_tilda


(array([[1., 1., 0., 0., 1.],
        [1., 1., 0., 1., 1.],
        [0., 0., 1., 0., 1.],
        [0., 1., 0., 1., 0.],
        [1., 1., 1., 0., 1.]]),
 array([[3, 0, 0, 0, 0],
        [0, 4, 0, 0, 0],
        [0, 0, 2, 0, 0],
        [0, 0, 0, 2, 0],
        [0, 0, 0, 0, 4]]))

In [19]:
norm_adjacency = np.linalg.inv(D_tilda) @ adjacency_matrix_tilda #@ np.linalg.inv(np.sqrt(D_tilda))
norm_adjacency_1 = adjacency_matrix_tilda @ np.linalg.inv(D_tilda)
norm_adjacency_2 = np.linalg.inv(D_tilda) @ adjacency_matrix_tilda @ np.linalg.inv(D_tilda)
norm_adjacency_3 = np.linalg.inv(np.sqrt(D_tilda)) @ adjacency_matrix_tilda @ np.linalg.inv(np.sqrt(D_tilda))
norm_adjacency,'',np.linalg.eig(norm_adjacency),'',"",norm_adjacency_1,'',np.linalg.eig(norm_adjacency_1),"",'',norm_adjacency_2,'',np.linalg.eig(norm_adjacency_2),"",'',norm_adjacency_3,'',np.linalg.eig(norm_adjacency_3)

(array([[0.33333333, 0.33333333, 0.        , 0.        , 0.33333333],
        [0.25      , 0.25      , 0.        , 0.25      , 0.25      ],
        [0.        , 0.        , 0.5       , 0.        , 0.5       ],
        [0.        , 0.5       , 0.        , 0.5       , 0.        ],
        [0.25      , 0.25      , 0.25      , 0.        , 0.25      ]]),
 '',
 (array([-0.09685647,  0.43018981,  1.        , -0.1830127 ,  0.6830127 ]),
  array([[ 6.43194517e-01, -5.58338266e-01, -4.47213595e-01,
           1.66081031e-16, -1.44623126e-16],
         [-4.15043586e-01, -8.11180117e-02, -4.47213595e-01,
           5.70563204e-01, -2.43049408e-01],
         [ 3.47691284e-01,  5.80989723e-01, -4.47213595e-01,
           4.17681254e-01,  6.64023332e-01],
         [ 3.47691284e-01,  5.80989723e-01, -4.47213595e-01,
          -4.17681254e-01, -6.64023332e-01],
         [-4.15043586e-01, -8.11180117e-02, -4.47213595e-01,
          -5.70563204e-01,  2.43049408e-01]])),
 '',
 '',
 array([[0.33333333, 0.2

In [6]:
#message passing
iteration = 1000
H = []
H_without_norm = []
h = node_feature
h_w = node_feature

for i in range(iteration):
    h = norm_adjacency@h
    h_w = adjacency_matrix_tilda@h_w
    H_without_norm.append(h_w)
    H.append(h)
    

C:\Users\User\AppData\Local\Temp\ipykernel_13768\1655878677.py:10: RuntimeWarning: overflow encountered in matmul
  h_w = adjacency_matrix_tilda@h_w
C:\Users\User\AppData\Local\Temp\ipykernel_13768\1655878677.py:10: RuntimeWarning: invalid value encountered in matmul
  h_w = adjacency_matrix_tilda@h_w


In [7]:
H[300],H_without_norm[100]

(array([[1.46666667, 1.53333333, 2.06666667, 1.73333333],
        [1.46666667, 1.53333333, 2.06666667, 1.73333333],
        [1.46666667, 1.53333333, 2.06666667, 1.73333333],
        [1.46666667, 1.53333333, 2.06666667, 1.73333333],
        [1.46666667, 1.53333333, 2.06666667, 1.73333333]]),
 array([[3.87368996e+52, 3.96673301e+52, 5.38202040e+52, 4.58133366e+52],
        [4.46011944e+52, 4.56724807e+52, 6.19679273e+52, 5.27489177e+52],
        [1.93684498e+52, 1.98336651e+52, 2.69101020e+52, 2.29066683e+52],
        [1.93684498e+52, 1.98336651e+52, 2.69101020e+52, 2.29066683e+52],
        [4.46011944e+52, 4.56724807e+52, 6.19679273e+52, 5.27489177e+52]]))

In [8]:
#for second
